inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - bin/*

Style/FileName:
  Exclude:
    - Gemfile

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
